[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "yarn build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [".next/*.json"]